### ISSUE TITLE
Overflow subfolder and obvious bug

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#10]
Here is my current config file (thanks for the changes you made to my old config i tried to copy any changes you made but i only saw the prefilter name change (i had made alot of changes since then like using subfolders alot))
(again Serch Data is my backup config (im using it since i cant attach my actual config))
[Serch Data.txt](https://github.com/lurkbbs/e621dl/files/3884949/Serch.Data.txt)
Edit2: made some changes again so i reuploaded it

Ok so obvious bug first when I was messing with the prefilters to download certain artists first and other such things i accedentlay downlaoded things that would have been filtered out with the ~female ~intersex ~ambiguous_gender that i had with seperating images and animations so I deleted my some files in my downloads and then ran the program again to get them back then i deleted my entire cache to delete all the images fully (didn't want them to take up space) but when i ran the program again my cache only filed up with new images not any of the old ones that were already downloaded 
       Basicly cache will only add new downloads not old ones if it gets deleted unless i delete everyting and run the program from scratch (fear this may be true for main folders and subfolders as well but not sure)
Edit1: This was before I started using the offical update don't know if this problem will continue

now i tried to make a misc. subfolder to keep all images that didn't go into any of my other subfolders since i didn't want loose images in the main folders. It sadly didn't really work and it also got some images that should be in other folders but were not since they were new post and they didn't have all the tags they should.
So what I was wondering is if it would be possible to make a overflow subfolder that will take any imges that wont go into any of the subfolders i made but would also be deleted every time the program is run so any images with updated tags can go into the subfolder they are supposed to go into and not the overflow folder

**Comment by lurkbbs** [comment]
There are errors in config.

"New Years" tag should be "New_years", just like in search field on e621.

In prefilters, this:

```
[<General>]
tag = ~female ~intersex ~ambiguous_gender Christmas Halloween Thanksgiving New_Years
```

will work only when on a single art there are tags `christmas`, `halloween`, `thanksgiving`, `new_year`; all on the same pic. Now, thing like this also won't work:

```
[<General>]
tag = ~female ~intersex ~ambiguous_gender ~Hug ~Christmas ~Halloween ~Thanksgiving ~New_Years
```

Since tag Christmas alone does not mean any of first three tags are present as well.

So my solution is conditions, that was made precisely for that.

```
[<General>]
tag = ~Hug ~Christmas ~Halloween ~Thanksgiving ~New_Years
condition = female | intersex | ambiguous_gender 
```
'|' means 'or'. This whole condition means download only those pics that have tag female _or_ tag intersex _or_ tag ambiguous_gender.
Here's short explanation how [Boolean expression](https://en.wikipedia.org/wiki/Boolean_expression) works:

So, say we have this condition

 -sad & ( (cute & happy) | (smile & closed_eyes) )
 
Let's look more on this. Replace in your mind tags with (does this post contains the tag. True if does, False if not), `-` with _not_ and `&` with `and`

If you remember what's noolean expressions, just skip this. If not, here is the explanation

`not True` means `False` and `not False` means `True`. That is obvious.

"X and Y" is True only when both X and Y also true. E.g. "I have an apple and I have a pen" is true only when you have both ingridients for an applepen.

"X or Y" is True if at least one of X or Y is true. E.g. "Do you watch me or do you watch organics?" answer is yes if you only watch captain Shepard, all organics in general, or if you do both.

So, say we have a post with all these tags.

`not True and ( (True and True) or (True and True) )`

so, we got

`False and (...)` which is always False. And that means no sad characters will be downloaded, whatever else tags are present.

Now, let's say nobody is sad on a pic. Then

`not False and ( ... )` --> `True and (...)` --> `(...)`

Moving on. Say, we have `cute` and `smile` tags, but we have not all others (including sad)

`not False and ( (True and False) or (True and False) )` -->

`True and ( (True and False) or (True and False) )` -->

`(True and False) or (True and False)` -->

`False or False` -->

`False`

So, despite no-one is sad, we won't get this pic.

Now, change that to cute & happy

`not False and ( (True and True) or (False and False) )` -->

`(True and True) or (False and False)` -->

`True or False` -->

`True`

We finally got something, despite nobody is smiling nor anyone's eyes are closed.

I hope this helps.

----

Also remember, only first five tags are actually sent to e621. So, if one day you wanted to make Criteria like this:

```
[<General>]
tag = ~artist_1 ~artist_2 ~artist_3 ~artist_4 ~artist_5 ~artist_6
```

you won't get artist_6 pictures. Or, more precisely, only those pictures which also have any of first five artists.

----

About cache. Yes, only new files will be added there. And fear not, download folders will be restored even if something is deleted from there, just not from cache but from another folder if copy exists.

----

Since you would need to remove incompletely tagged images from everywhere to actually free space, I have another suggestion: said files should be automatically removed from folders, and if they are only in a cache, then from cache as well.

----

Also, preferable solution is to not download these wrong tagged files in the first place. I'll try to produce some condition / tag combination to that effect. For now, take edited config.

[config.ini.txt](https://github.com/lurkbbs/e621dl/files/3888411/config.ini.txt)

**Comment by huskelord** [comment]
Thanks for the lession and the help.
Edit1: i think i just figured out how to fix my misc folder

[*Misc.]
Tags = -Solo
blacklisted = male/female intersex/female intersex/male intersex/intersex female/female

And i would just add the tags that make any new subfolders in the blacklisted
This would also help if tags i didn't want to show up by keeping them contained in the misc. folder (i would just have to remake the misc. folder after deleting it and finding the problem.

now im just wondering if there was a way to make any updates to a posts tag change its folder location like if a post has an intersex/intersex tag but isn't supposed to have that tag once the tag gets removed it gets removed from the intersex/interex folder (and from cache if it wasn't supposed to be downloaded anyways.)

**Comment by lurkbbs** [comment]
I suggest alternative config, with conditions preventing untagged downloads in the first place.

[config.ini.txt](https://github.com/lurkbbs/e621dl/files/3888668/config.ini.txt)

Edit:
Ooops, forgot to remove offline mode. Also, check out `format` option.
[config.ini.txt](https://github.com/lurkbbs/e621dl/files/3888763/config.ini.txt)

**Comment by huskelord** [comment]
I want the misc folder because I still want those diffrent images. I dont want a folder for every little thing but i also dont want any images mixed in with folders (its anoying for me) thus the misc. folder to keep it all clean while helping if i make a mistake when downloading like I did before. 
The I didn't know what the problem was until you remined me of the 5 tag limit so that helped me come up with a solution.

The deletion of images from a folder when a tag changes is someting I still sugest if it is some thing that doesn't happen already since it would save space by deleting any posts that were downloaded to a folder and cache just because it didn't have a blacklisted tag when it was supposed to. or taking it from my overlow folder after it gets put into the correct folder when the tags get updated.

**Comment by lurkbbs** [comment]
Ah. Then yes, your way surely works.

But I need to clarify something. Since you're using [hardlinks](https://en.wikipedia.org/wiki/Hard_link), _you can delete all downloads folder and it won't save space_. But that's a good thing, as space was already saved, that's the whole point of the hardlinks.

But that also mean that:
* Deletion of the misc folders alone won't save space. Seriously, try measure free space, then delete whole `downloads` folder and measure again. If it changes drastically, something is wrong.
* If something is not prevented to download to at least one folder, it will take space. Luckily, again, there can be a lot of dupes, 4096 to be exact.

And that mean that you can ignore these misc folder if free space is the only concern. But yes, removal of files not belonging to a folder anymore is a good idea, at least for convenience.

**Comment by huskelord** [comment]
Thanks for the all the help you have given me and for keeping this entire thing running just want to say I appreicate it. Keep up the good work and thanks once again.
(this issue is done so if you want to you can close it.)

**Comment by lurkbbs** [comment]
Thanks. It's actually nice to read that.

I'll close this then, just remind me to make autodeletion of pics that don't belong into a folder anymore when other issues are done.
