### ISSUE TITLE
Minus Overview Subfolder

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#11]
Im trying to make a folder for fictional species but the only way I can get it to work is by doing this

[Species/Fictional/au_ra]
Tag = au_ra 

[Species/Fictional/Merfolk]
Tag = Merfolk

because when i do this

[Species/Fictional]
subfolder = au_ra merfolk

I will get a animated and imgages folder that will contain my entire cache since it doesn't have a limiting tag. I get these folders because i have subfolders = Images Animated in my defaults 

[Defaults]
days = 99999
ratings = s, q, e
min_score = 0
min_favs = 0
subfolders = Images Animated
posts_from = api

what im wondering is if it would be possible to make way to way for a certain surch not contain any overall subfolders

**Comment by lurkbbs** [comment]
Yes, there is such way. It even implemented for subfolders, e.g.

```
[*Fictional]
subfolder = au_ra merfolk

[Species]
subfolder = *Species
```

should work, but looks like I forgot to make main folder a special case. thanks for notifying about this bug, I'll fix it during next week, most likely Saturday, GMT+3.

**Comment by huskelord** [comment]
just a random question would it be possible to change the download type from api to db during one run my having the default section remade before the section that i want to only be downloaded from the db and not api while still having some intital stuff downloaded via api

[Defaults]
days = 99999
ratings = s, q, e
min_score = 0
min_favs = 0
subfolders = Images Animated
posts_from = api

whatever i want updated from the site and all that like oral_penetration, etc

[Defaults]
days = 99999
ratings = s, q, e
min_score = 0
min_favs = 0
subfolders = Images Animated
posts_from = db

whatever I wanted sorted into files whitout having to download every single one of its type like diffent species without having to make subfolders for it

I don't necesarly think this should be thing if it is not already just something I was curious about and thought i would ask

**Comment by lurkbbs** [comment]
I'm not sure I get it.

You want, during a single run, to download, say, only post uploaded last 30 days and then download copy everything else from cache?

Or do you wan't to download only for some sections, and for everything else full_offline should be in effect?

Also, let's say we can run one config, then another in sequence, would it solve your problem?

Just in case of yes, here's a quickfix BAT script. It will use `config1.ini` and then `config2.ini`.
code is simple:

```
copy /y config1.ini config.ini
e621dl.exe

copy /y config2.ini config.ini
e621dl.exe

pause
```

so you can edit it to add more configs. Just **be sure to backup original config.**
sending zipped, because Github.
[multiple_configs.zip](https://github.com/lurkbbs/e621dl/files/3923338/multiple_configs.zip)

It's a great idea to add multiple configs and then process them one by one, anyway

**Comment by huskelord** [comment]
The multiple configs work and would definitly fix my problem but I ran into another one. I cant seem to get the database to work
here are my congis (api is first one db is second as my config order)

[Config Data (API).txt](https://github.com/lurkbbs/e621dl/files/3925001/Config.Data.API.txt)
[Config Data (DB).txt](https://github.com/lurkbbs/e621dl/files/3924990/Config.Data.DB.txt)

I'm guessing that the problem is that the main tags are not verified during the api download but I can't be sure of that because I dont know how i would verify them without donwloading the entire serch group. This is probably not likely however since the animal base should have donwloaded at least.

**Comment by lurkbbs** [comment]
I'll check it tomorrow then

**Comment by lurkbbs** [comment]
Tomorrow comes today. And hey, post error message next time.
In short, incorrect name of subfolder:

```
;Get rid of (Tag = ) when main file bug is fixed
[Species/elf]
...
subfolders = elf_-specified
```

while

```
[*elf-specified]
...
```

same for `taur-specified` / `taur_-specified`, btw.

**Comment by huskelord** [comment]
Thanks I missed that but sadly that not it. It wont download anything it just goes through the tag verification and closes like it's done no error message or anything. (Also this happened before and after the multi config)

**Comment by huskelord** [comment]
NVM I just got home and it worked. don't know why i didn't get an error code when it would'nt work before however.

**Comment by lurkbbs** [comment]
That's strange. So, just to be clear, do you use `e621dl.exe` directly or `e621dl_noclose.bat`? If it's first, than use second in case of errors. It's this way because I don't know yet how to show errors without closing the app and also support window closing with `x` button during downloading. This, and also because simple scripting like with `multiple_configs.bat` would be hard. And because I don't wanna, yeah.

If you already use `e621dl_noclose.bat` and window actually closes, this is extremely strange. One reason why it's like that is stray right mouse click or key press. Then at first e621dl.exe crashes, then `pause` app thinks key already pressed and exits, and then window closes.

**Comment by huskelord** [comment]
I dont remember it might have been the .exe and not the no close but either way it's working now. It was the problem with the _ I just didnt seem to get a error and I guess I never used it with the no close for some reason.

**Comment by lurkbbs** [comment]
And fixed. 

```
[Species/Fictional]
subfolder = au_ra merfolk
```

should work now.

**Comment by huskelord** [comment]
I'll take a look once I get home.

**Comment by huskelord** [comment]
It's not working and i can't get the no_close to work either.

this is the error code i get witht eh no_close

C:\WINDOWS\system32>e621dl.exe
'e621dl.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>pause
Press any key to continue . . .

the program will close but I don't know when


I know it's off topic but this is another aspect that I was hopeing the updated program to fix that I either forgot to mention or was not clear

I have a .Everyting subfolder that I want to be an like my Images and Animated subfodler but I dont want it to go into my sub subfolders. 

I don't know if you will understand my problem but what Im asking is there a way to some subfolders to not be influinced by the Defualt section subfolders

Edit1: I thought it was working before but I relize that i was still using the old exe file not the new one. (i didn't save any changes to the config file so nothing was changed)
Edit2: Long story short I accedentaly deleted everyting even from my recycle bin from my recycle bin
except my current config files but i cant seem to get anyting to work. and since i cant get the no_close to work or the previous versions to work so I can see whats wrong im stuck. yay.

**Comment by lurkbbs** [comment]
For `.everything`:
So, you want `.everything` to be in every section, but only on first level, yes?

For everything else. That's just wow, but It feels like I know why no_close is not working. It looks like it was launched as admin, and `noclose` from release does not support it. Take this:
[e621_noclose.zip](https://github.com/lurkbbs/e621dl/files/3934897/e621_noclose.zip)

I will also update release version
Edit: that is, in release page. Release version of e621dl stays the same.

Edit2: As for everything is deleted, let's just create new folder, download `e621dl.exe` and `e621_noclose.bat` and try again.

**Comment by huskelord** [comment]
Yes to the .everyting. and sorry for for venting a bit at the end I figured it shouldnet be too hard to get back up and runing once everyting is fixed.
Edit1: the no_close works now could you do the same with the multi_config too
Edit2: there is a problem with the program.
Ran the program with no_close and it will run and verify all the tags but it wont download anything it just shuts off
Here is what it shows after it has run its course

status: All complete
checked tag: all tags are valid
posts so far: None so far
last file downloaded: None so far
current section: <everything>
last warning: None so far
connection retries: None so far
already exist: None so far
downloaded: None so far
copied: None so far
filtered: None so far
not found on e621: None so far

D:\e621dl>pause
Press any key to continue . . .

Here my config data (the 3 and the 4 are to keep them at the top of the file.
[3 Config Data (API).txt](https://github.com/lurkbbs/e621dl/files/3934919/3.Config.Data.API.txt)
[4 Config Data (DB).txt](https://github.com/lurkbbs/e621dl/files/3934920/4.Config.Data.DB.txt)

Edit3: redownloaded the previous version and ran it with the no_close and it didn't work so it is probably a problem in my config file so ill start looking and see if i find anything there. (also the api config data is the only one I can test since I need something already downloaded to even use the second one.
Edit4: I'm an ideot. it was set to db not api in the default. God that was a stupid mistake. sorry for the trouble. with the stuff above.

**Comment by huskelord** [comment]
Just currious but do you know a way to get rid of the UAC popup or make it so I dont have to apporve it every time it wan't to open the e621dl.exe window

Like could you make the multi_config bat able to run on administrator
And would doing that make it run both the e621dl program in the cmd.exe window instead of just opening the e621dl.exe window twice.

If it seem like to much of a hassel don't worry about it I'm basicly just letting my mouth (hands) run with my brain.

Anyway ill let you know if eveything with the subfolder's work on my end once I get my storage updated.

**Comment by lurkbbs** [comment]
Here:
[multiple_configs.zip](https://github.com/lurkbbs/e621dl/files/3934956/multiple_configs.zip)

But you can run as regular user, since you enabled developer mode. Just disable run as admin for `e621dl.exe`.

Edit: also, this version has an annoying but harmless bug, showing extremely high number of filtered images. That's just visual bug, don't worry.

**Comment by huskelord** [comment]
Its working thanks I'll need it to run for a while to see if everyting checks out on my end but it sounds like everyting will work out well. Also how is the progress on the blacklist folder

**Comment by lurkbbs** [comment]
None. Actually, it took me about 4 hours to just fix this bug, mostly because of `max_downloads` option. And introduce a new one, yeah 😅. So, I'm resting now and  maybe tomorrow evening I'll start to work on completely new feature, file removal. Maybe tomorrow evening this will be done. 

And for now, I'm closing this issue
