### ISSUE TITLE
Virus detected in new .exe

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#17]
So i tried to download the new release but whenever i tried to download it it stops me saying there is a virus detected.

**Comment by lurkbbs** [comment]
False positive.

First, chrome warning is based on "not a lot of people download it yet", which is bullshit metrics in the first place.

Second, it's a [known problem for pyinstaller](https://www.reddit.com/r/learnpython/comments/bp9zim/pyinstaller_executable_has_virus_on_one_machine)

Check out [virustotal](https://www.virustotal.com/gui/file/48c5575670d01fb78ec2cbfd30dff54bb61676de46585519e5d4d67cc36f5cbd/detection), out of 79 only 9 mark pyinstaller as a bad boy.

Reason why it's like that in the first place is also understandable. I build e621.exe with pyinstaller, a tool that is little more than self-extract archive with Python, required python modules and the script itself. Than means app is self unpacks some executable without user notification.
Then it looks for system cryptography module, needed to work with encrypted webpage transmission (google HTTPS, SSL or TLS for details). And finally, it looks for _pyvenv.cfg_ file in user profile folder, because pyinstaller uses venv internally (it doesn't really matter what venv is).

Now let's combine this three together. self-extract + cryptomodules + user folders. If I didn't know better, I would assume cryptolocker ransomware myself. And those 9 antivirus are either dumb or paranoid enough to report malware just in case.

But, if you're afraid anyway, you can download source code and just unpack and run "*noclose_py*" version.

**Comment by huskelord** [comment]
got it thanks
