### ISSUE TITLE
script crashes when parsing config

### ISSUE THREAD

**Issue by jahkyah** [lurkbbs/e621dl#28]
Hello! Hope you are well!

When it finishes downloading field dics, it crashes

Below is a screenshot of the crash

![image](https://user-images.githubusercontent.com/53247317/81906015-902fbc00-9593-11ea-861f-bd76d8b5b8e1.png)

I am not sure if it is on my end but I could of sworn it was working fine yesterday when I was on Manjaro.

**Comment by lurkbbs** [comment]
OK, first of all, make sure all dependencies are there

```
pip install requests colorama natsort brotli
```

Didn't work with Arch much, maybe there's some other way to install them, probably

```
sudo pacman -S python-brotli python-colorama python-natsort python-requests
```

Brotli is the most recent dependency, added when I finally found HTTP headers and cookies that tell Cloudflare that yes, e621dl is indeed the same thing as Chrome with spoofed user-agent. Since e621 servers prefer brotli if given choice between it, plaintext or gzip, I leaved it be.

Anyway, "it works on my machine", if you have trouble with yours, please send me your config(s) either here in attachment, or on my email (lurkbbs <squigly> gmail.com) or PM me on e621 (lurkbbs).

**Comment by jahkyah** [comment]
Thank you, I switched back to win 10, I will let you know how it goes when
I do pip install brotli !

The last time I used the script was when I was using arch. I am on windows
10 now haha

**Comment by jahkyah** [comment]
Thank you!

Installing brotli has fixed this issue.

I was not aware of this new dependency.

Before I made this issue I redownloaded the script + the libs for it and read the readme and did not see Brotli on the list. Usually it is Natsort, Colorama, and requests

Thank you for the help!

**Comment by lurkbbs** [comment]
You're welcome!

I'll add dependency check to my TODO then 🙂
