### ISSUE TITLE
Won't Get Past the 'Building Downloaded Files dict' status

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#34]
I don't know why i didn't notice this before but the program seems to not be able to get pass the 'Building Downloaded Files dict' status after i have run the program to completion. If it is still running and just to needs time to finish, it taking over 5 minitues to do so. The only solution i know is to delete the downloads folder and all generated files to get it started again.

**Comment by lurkbbs** [comment]
Huh.

On a slow drive with lots and lots of files in lots and lots of folders it's possible. And since last time it took 30+ minutes to delete it all, and that's on a fast drive with a fast commanline tool, there _is_ a lot files and folders. Try wait around 10-15 minutes. You can open Task Manager and check if the app is growing in memory and/or actively uses disk.

I can add some indication if it's still processing (e.g. current processed folder) this weekend.

**Comment by huskelord** [comment]
Thanks that would help alot
