### ISSUE TITLE
cant download (at starbucks)

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#5]
I'm at starbucks because i moved to an apartment and have not been able to get internet up and running and was hoping i could get some downloads done before then. this is a video that I have taken of the code that shows up before shut down. I don't know why id didn't work and thought you might be able to tell me.
![screenshot 1](https://user-images.githubusercontent.com/47302136/53704378-e32fb000-3de1-11e9-8644-f662b9f191ca.png)
![screenshot 3](https://user-images.githubusercontent.com/47302136/53704412-17a36c00-3de2-11e9-9589-21f352f98dfa.png)

**Comment by huskelord** [comment]
nvm i found out. its their companies protection. just use vpn to go around it.

**Comment by lurkbbs** [comment]
Good to know. SSLError is somewhat strange way to announce it, I guess some authorization page must be visited first, not sure if from any browser or from specific one, but, since VPN worked, I guess that's not the case anyway.

Late answer again. As it turns out, I won't receive email of new issue for my own repo by default. God, this is strange.
